name: "PR Checkbox Checker"
description: "Checks if all checkboxes in a pull request description are checked"
author: "kromiii"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  github-token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  github-api-url:
    description: "GitHub API URL (for GitHub Enterprise Server)"
    required: false
    default: ${{ github.api_url }}

runs:
  using: "composite"
  steps:
    - name: Set execute permission
      run: chmod +x ${{ github.action_path }}/check-boxes.sh
    - name: Check boxes
      shell: bash
      run: ${{ github.action_path }}/check-boxes.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_API_URL: ${{ inputs.github-api-url }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
